apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-backend-app
spec:
  selector:
    matchLabels:
      app: dental-backend-app
  template:
    metadata:
      labels:
        app: dental-backend-app
    spec:
      containers:
        - name: dental-backend-app
          image: 754071320815.dkr.ecr.ap-southeast-1.amazonaws.com/dental-express-eks:latest  
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: tcp
              containerPort: 3000
      nodeSelector:
          kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  name: dental-backend-app
spec:
  selector:
    app: dental-backend-app
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer